### ISSUE TITLE
image not displayed

### ISSUE THREAD

**Issue by abdulrahman3D** [femioladeji/react-slideshow#45] opened 2019-10-05 18:22 UTC
Image not displayed although the same image path working on another js file in the same directory.

`import React, { Component }  from 'react';
import { Zoom } from 'react-slideshow-image';
import {  Image,  } from "react-bootstrap"

const images = [
    "../../static/img/hero-illustration.png",
    "../../static/img/kacst.png"
  ];

  const zoomOutProperties = {
    duration: 5000,
    transitionDuration: 500,
    infinite: true,
    indicators: true,
    scale: 0.4,
    arrows: true
  }

class SlidShow extends Component {
    state = {  }
    render() { 
        return (
            <div className="slide-container">
              <Zoom {...zoomOutProperties}>
                {
                  images.map((each, index) => <img key={index} /*style={{width: "100%"}}*/ src={each} />)
                }
              </Zoom>
            </div>
          )
    }
}
 
export default SlidShow;`

**Comment by femioladeji** [comment] 2019-10-08 16:41
@abdulrahman3D sorry for my late response. Have you been able to fix it now? If not is there any error on your console?

**Comment by femioladeji** [comment] 2019-11-24 23:32
@abdulrahman3D I want to believe you've been able to fix this. So I'll close the issue

**Closed by femioladeji** 2019-11-24 23:32 UTC

**Comment by amirkhh** [comment] 2020-04-16 11:32
I have this issue and console doesn't show any error. How can I fix it ?

**Comment by femioladeji** [comment] 2020-04-16 11:41
@amirkhh are you sure the image path is correct? Can you replicate it on [https://codesandbox.io/](https://codesandbox.io/) so that I can have a better look?

**Comment by amirkhh** [comment] 2020-04-17 12:43
Yes, I'm sure.
I've found the problem. When I use direction: rtl in body tag in style all of images aren't load.

How can I fix it @femioladeji ?

https://codesandbox.io/s/elastic-mestorf-ryidb?file=/src/styles.css

**Comment by femioladeji** [comment] 2020-04-17 20:37
HI @amirkhh I've seen the issue. It's really quite tricky to debug because the slideshow relies on the `transform: translate` CSS style. Can you apply the `direction: rtl` style to the particular div you want to display from right to left so that the slideshow portion won't be affected with the style

**Comment by amirkhh** [comment] 2020-04-18 10:49
Hi @femioladeji, It's not working for me. 
Could you refactor it in [codesandbox.io](https://codesandbox.io/s/elastic-mestorf-ryidb?file=/src/styles.css) for me ? Thank you.

**Comment by femioladeji** [comment] 2020-04-18 15:36
@amirkhh check this https://codesandbox.io/s/goofy-shamir-mfsfm?file=/src/App.js

**Comment by amirkhh** [comment] 2020-04-19 09:18
Thank you @femioladeji, but I couldn't remove rtl direction from body tag so I put in body tag and set direction: ltr to slide show container (..slide-container) and it's solved.

https://codesandbox.io/s/elastic-mestorf-ryidb?file=/src/styles.css:85-101

**Comment by Temitayo-spec** [comment] 2022-08-29 16:25
My slideshow stopped working after i deployed my app to netlify but it works on localhost

**Comment by femioladeji** [comment] 2022-08-29 16:33
@Temitayo-spec what version are you using? Also is the website built with next js or it only uses react?

**Comment by Temitayo-spec** [comment] 2022-08-30 00:16
it's built with Next.js actually, don't know if there's an issue with this
SWC... I'm getting this animate is not defined error

**Comment by jeypc** [comment] 2022-12-10 13:01
@Temitayo-spec did you manage to solve the issue? I'am having the same issue on nextjs (production build), but it's working fine on development mode

**Comment by Temitayo-spec** [comment] 2022-12-10 14:56
not at all, it only works in Development mode.

**Comment by femioladeji** [comment] 2022-12-10 17:17
@Temitayo-spec @jeypc what version of nextjs are you using? I think the issue is connected to this #190 
Can you create a small reproducible github repo so that I can take a deeper look at this

**Comment by jeypc** [comment] 2022-12-12 04:51
move the animation function out of the transitionSlide function seems fix the problem

**Comment by Temitayo-spec** [comment] 2022-12-12 13:59
i don't if it has been fixed, but the repo link is
https://github.com/Temitayo-spec/Kenneth-landing-page

**Comment by Temitayo-spec** [comment] 2022-12-12 14:00
Oh, i'll check that out, Thanks.
